version: '3'
services: 
    php7.4.3-tengine2.3.2:
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - "./src:/etc/nginx/project/"