version: '3'
services: 
    tpwork:
        image: ijoery/tpwork:latest
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            # 将源码挂载到指定路径，已经做了PATHINFO路由重写
            - "./tpwork:/etc/nginx/project/"