version: '3'
services: 
    tengine_php:
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - "./src:/etc/nginx/project/"