version: '3'
services: 
    tpwork:
        # build: 
        #     dockerfile: Dockerfile
        #     context: .
        image: ijoery/tpwork:latest
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - "./tpwork:/etc/nginx/project/"